services:
  backend:
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    env_file:
      - .env
    # FastAPIの8000番ポートをホストOSの8000番ポートにマッピング
    ports:
      - "8000:8000"
    # コードの変更をリアルタイムで反映させるため、ホストOSのコードをコンテナにマウント
    volumes:
      - ./src/backend:/app
    depends_on:
      rdb:
        condition: service_healthy
    # --reloadはマウントが条件なのでdocker-compose.ymlで実行
    command: >
      bash -c "poetry config virtualenvs.create true &&
               poetry install --no-interaction --no-ansi --no-root &&
               poetry run python init_db.py &&
               poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    env_file:
      - .env
    # Next.jsの3000番ポートをホストOSの3000番ポートにマッピング
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
      # node_modulesは同期せず、匿名ボリュームを使用してコンテナ内に保存する
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      rdb:
        condition: service_healthy

  rdb:
    image: mysql:8.4
    # 落ちたときに自動で再起動
    restart: always
    command: --default-time-zone='+09:00'
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  mysql:
